android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.nonTransitiveRClass=false
android.nonFinalResIds=false

#alternate band-aid for the `jvm target compatibility should be set to the same Java version` problem:
#kotlin.jvm.target.validation.mode = IGNORE

org.gradle.daemon=true
org.gradle.configureondemand=true
kotlin.compiler.execution.strategy=in-process

# Enable incremental compilation for Java
org.gradle.incremental=true

# Enable incremental compilation for Kotlin
kotlin.incremental=true
